name: BTC Levels Bot

on:
  schedule:
    - cron: '0 * * * *'      # каждый час в 00 минут
  workflow_dispatch:         # можно запустить вручную

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install requests python-telegram-bot==20.7
          python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
